# Generated by Django 3.2.7 on 2021-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_type', models.CharField(default='cuurent address', max_length=30)),
                ('add_id', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(default='uppp', max_length=100)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_first_name', models.CharField(max_length=50)),
                ('emp_midle_name', models.CharField(max_length=50)),
                ('emp_last_name', models.CharField(max_length=50)),
                ('email_add', models.EmailField(max_length=30)),
                ('contact_no', models.CharField(max_length=20)),
                ('pancard_no', models.CharField(max_length=20)),
                ('adhaar_no', models.IntegerField()),
                ('blood_gruop', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rel_EmpProfile_Add_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('add_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
