# Generated by Django 3.2.7 on 2021-09-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_alter_permanent_address_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permanent_address',
            name='empid',
        ),
    ]
