# Generated by Django 3.2.7 on 2021-09-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_permanent_address_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200)),
                ('assigned_by', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('assigned_date', models.DateField(max_length=200)),
                ('complition_date', models.DateField(max_length=200)),
            ],
        ),
    ]
