# Generated by Django 3.2.7 on 2021-09-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
    ]
