# Generated by Django 3.2.7 on 2021-09-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_rename_task_task1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Task',
        ),
    ]
