# Generated by Django 3.2.7 on 2021-09-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_rename_task1_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
