# Generated by Django 3.2.7 on 2021-09-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0012_employee_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='profile_img',
            field=models.ImageField(upload_to='', verbose_name=models.ImageField(default='images/profile3.jpg', upload_to='images/')),
        ),
    ]
