# Generated by Django 3.2.5 on 2021-09-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0013_alter_employee_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='profile_img',
            field=models.ImageField(default='images/profile3.jpg', upload_to='myimage'),
        ),
    ]
