# Generated by Django 4.0.4 on 2022-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0016_department_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
