# Generated by Django 4.0.4 on 2022-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0017_employee_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='userpassword',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
