# Generated by Django 4.0.4 on 2022-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0018_employee_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauthentication',
            name='username',
            field=models.CharField(default='admin', max_length=50, unique=True),
        ),
    ]
