# Generated by Django 4.0.4 on 2022-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0020_remove_employee_profile_email_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_profile',
            old_name='emp_name',
            new_name='emp_Fname',
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='emp_Lname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
