# Generated by Django 4.0.4 on 2022-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0021_rename_emp_name_employee_profile_emp_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginauthentication',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
