# Generated by Django 4.0.4 on 2022-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0022_loginauthentication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='complition_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
