# Generated by Django 4.0.4 on 2022-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0023_alter_task_assigned_date_alter_task_complition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='complition_date',
            field=models.DateField(max_length=200),
        ),
    ]
