# Generated by Django 4.0.4 on 2022-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0024_remove_employee_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='complition_date',
            field=models.CharField(max_length=200),
        ),
    ]
